import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Link from "next/link";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "K-Goods",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-6">
          <div className="cols-span-1 bg-red-200 max-h-screen">
            <Sidebar />
          </div>
          <div className="bg-white col-span-5 p-4 px-6">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
